import{S as f,i as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function d(s){const n=`https://pixabay.com/api/?key=42530845-4f1978a0628226c655e2788d5&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const l=document.querySelector(".gallery");function m({largeImageURL:s,webformatURL:o,tags:r,likes:n,views:e,comments:t,downloads:i}){return`<a href="${s}">
    <img src="${o}" alt="${r}"/>
    <div class="info-box">
    <p class="info"><b>Likes</b> ${n}</p>
    <p class="info"><b>Views</b> ${e}</p>
    <p class="info"><b>Comments</b> ${t}</p>
    <p class="info"><b>Downloads</b> ${i}</p>
    </div></a>`}function p(s){const o=s.map(m).join("");return l.insertAdjacentHTML("beforeEnd",o)}const g="/goit-js-hw-11/assets/icon-8fe9c699.svg",c=document.querySelector(".form"),a=document.querySelector(".loading");c.addEventListener("submit",s=>{s.preventDefault(),l.innerHTML="";const o=c.search.value.trim().replace(/\s/g,"+");o&&o!==""&&(a.classList.add("loader"),d(o).then(r=>{a.classList.remove("loader"),r.total!==0?(p(r.hits),new f(".gallery a",{captionsData:"alt",captionDelay:100}).refresh()):u.show({iconUrl:g,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",color:"#FF6868",position:"topRight",progressBarColor:"#ffffff",close:!1,timeout:2e3})}).catch(r=>console.log(r))),c.reset()});
//# sourceMappingURL=commonHelpers.js.map
